### PR TITLE
New licensing: LGPLv3

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Changed license to LGPLv3
- Updated Readme.md accordingly
- Updated all sources headers (.h and .cc) to point on correct licensing terms, copyrights and author list
- Updated TravisCI status url in Readme.md

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
@dreyling @eyiliu @arummler Is it compatible with EUDAQ ?

**Comment by rete** [comment]
@ebrianne Is it fine for AHCal monitoring ?

**Comment by ebrianne** [comment]
Hum, I don't know. I think in principle it is not a problem from our side. I ll need to see with Jiri (@jkvas)

**Comment by eyiliu** [comment]
eudaq is LGPLv3.

**Comment by rete** [comment]
If you agree with this new licensing terms, please add your review and approve

**Pull request merged**
